# Generated by Django 4.2.8 on 2024-02-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('page', models.IntegerField(default=1)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online.author')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='online.category')),
            ],
        ),
    ]
