# Generated by Django 5.0.1 on 2024-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=225),
        ),
    ]
