# Generated by Django 5.0.1 on 2024-02-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_alter_author_email_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='authors'),
        ),
    ]
